name: Flatpak Build

on:
  schedule:
    - cron:  '30 7 * * 1,5'
    
  workflow_dispatch: 
  
jobs:
  build:
    name: Build on Linux
    runs-on: ubuntu-20.04
    steps:
    - uses: actions/checkout@v2

    - name: Environment Setup
      run: |
        sudo apt-get purge cmake -y
        sudo apt-get update
        sudo apt-get install autoconf automake autopoint appstream build-essential cmake git libass-dev libbz2-dev libfontconfig1-dev libfreetype6-dev libfribidi-dev libharfbuzz-dev libjansson-dev liblzma-dev libmp3lame-dev libnuma-dev libogg-dev libopus-dev libsamplerate-dev libspeex-dev 
        sudo apt-get install libtheora-dev libtool libtool-bin libturbojpeg0-dev libvorbis-dev libx264-dev libxml2-dev libvpx-dev m4 make meson nasm ninja-build patch pkg-config python tar zlib1g-dev
        sudo apt-get install libva-dev libdrm-dev gstreamer1.0-libav intltool libappindicator-dev libdbus-glib-1-dev libglib2.0-dev libgstreamer1.0-dev libgstreamer-plugins-base1.0-dev libgtk-3-dev libgudev-1.0-dev libnotify-dev libwebkit2gtk-4.0-dev
        sudo pip3 install meson
        sudo apt-get install flatpak flatpak-builder
        sudo flatpak remote-add --if-not-exists flathub https://dl.flathub.org/repo/flathub.flatpakrepo
        sudo flatpak install -y flathub org.freedesktop.Sdk//21.08
        sudo flatpak install -y flathub org.freedesktop.Platform//21.08
        sudo flatpak install -y flathub org.gnome.Platform//41
        sudo flatpak install -y flathub org.gnome.Sdk//41
        sudo apt-get upgrade -y
        
    - name: Download the Source Code
      run: |
        git clone https://github.com/HandBrake/HandBrake.git
    
    - name: Build HandBrake
      run: |
        free -m -t
        cd HandBrake
        ./configure --launch-jobs=1 --flatpak
        free -h && sudo sysctl -w vm.drop_caches=3 && sudo sync && echo 3 | sudo tee /proc/sys/vm/drop_caches && free -h
        cd build
        nice make pkg.create.flatpak --jobs=1

    - name: Upload Assets
      uses: actions/upload-artifact@v2
      with:
        name: HandBrake-Flatpak
        path: ./HandBrake/build/pkg/flatpak/*.flatpak


  deploy_nightly:
    name: Deploy Nightly Build
    runs-on: ubuntu-latest
    needs: build
    steps:
      - uses: actions/checkout@v2
       
      - name: Download Artifacts - Flatpak Binaries
        uses: actions/download-artifact@v2
        with:
          name: HandBrake-Flatpak
          path: lin/
          
      # Generate Hashes
      - name: Generate SHA265 Hashes
        run: |
          cd lin
          sha256sum * > sha256.txt
          cp sha256.txt ../.github/workflows/
          cd ..
          cd .github/workflows/
          sed -e 's/  / | /' -i sha256.txt
          sed -e 's/^/| /'  -i sha256.txt
          sed -e 's/$/ |/' -i sha256.txt
          cat sha256.txt >> lin_rel_body.md
      
      # Publishing the Release
      - name: Remove the old Release
        uses: dev-drprasad/delete-older-releases@v0.2.0
        with:
          keep_latest: 0
          delete_tag_pattern: "lin"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          
      - uses: ncipollo/release-action@v1
        with:
          artifacts: "lin/*.*"
          name: "Snapshots for Linux"
          bodyFile: .github/workflows/lin_rel_body.md
          prerelease: true
          replacesArtifacts: false
          allowUpdates: false
          tag: lin
          token: ${{ secrets.GITHUB_TOKEN }}
